/**
 * generated by Xtext 2.12.0
 */
package org.eclipse.gemoc.xdsmlframework.behavioralinterface.behavioralInterface.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.eclipse.gemoc.xdsmlframework.behavioralinterface.behavioralInterface.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class BehavioralInterfaceFactoryImpl extends EFactoryImpl implements BehavioralInterfaceFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static BehavioralInterfaceFactory init()
  {
    try
    {
      BehavioralInterfaceFactory theBehavioralInterfaceFactory = (BehavioralInterfaceFactory)EPackage.Registry.INSTANCE.getEFactory(BehavioralInterfacePackage.eNS_URI);
      if (theBehavioralInterfaceFactory != null)
      {
        return theBehavioralInterfaceFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new BehavioralInterfaceFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BehavioralInterfaceFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case BehavioralInterfacePackage.BEHAVIORAL_INTERFACE: return createBehavioralInterface();
      case BehavioralInterfacePackage.EVENT: return createEvent();
      case BehavioralInterfacePackage.INPUT_EVENT: return createInputEvent();
      case BehavioralInterfacePackage.OUTPUT_EVENT: return createOutputEvent();
      case BehavioralInterfacePackage.EVENT_PARAMETER: return createEventParameter();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BehavioralInterface createBehavioralInterface()
  {
    BehavioralInterfaceImpl behavioralInterface = new BehavioralInterfaceImpl();
    return behavioralInterface;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Event createEvent()
  {
    EventImpl event = new EventImpl();
    return event;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public InputEvent createInputEvent()
  {
    InputEventImpl inputEvent = new InputEventImpl();
    return inputEvent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public OutputEvent createOutputEvent()
  {
    OutputEventImpl outputEvent = new OutputEventImpl();
    return outputEvent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EventParameter createEventParameter()
  {
    EventParameterImpl eventParameter = new EventParameterImpl();
    return eventParameter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BehavioralInterfacePackage getBehavioralInterfacePackage()
  {
    return (BehavioralInterfacePackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static BehavioralInterfacePackage getPackage()
  {
    return BehavioralInterfacePackage.eINSTANCE;
  }

} //BehavioralInterfaceFactoryImpl
