/**
 * generated by Xtext 2.12.0
 */
package org.eclipse.gemoc.xdsmlframework.behavioralinterface.behavioralInterface.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.gemoc.xdsmlframework.behavioralinterface.behavioralInterface.BehavioralInterfacePackage;
import org.eclipse.gemoc.xdsmlframework.behavioralinterface.behavioralInterface.OutputEvent;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Output Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class OutputEventImpl extends EventImpl implements OutputEvent
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OutputEventImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BehavioralInterfacePackage.Literals.OUTPUT_EVENT;
  }

} //OutputEventImpl
