<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="genericevent" nsURI="http://www.eclipse.org/gemoc/event/generic"
    nsPrefix="genericevent">
  <eClassifiers xsi:type="ecore:EClass" name="GenericEvent" eSuperTypes="event.ecore#//Event">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ruleID" eType="#//RuleID"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.gemoc.commons.value.model/model/value.ecore#//Value"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuleID"/>
  <eClassifiers xsi:type="ecore:EClass" name="RuleFQN" eSuperTypes="#//RuleID">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fqn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuleRef" eSuperTypes="#//RuleID"/>
</ecore:EPackage>
