/*
 * generated by Xtext 2.12.0
 */
package org.eclipse.gemoc.xdsmlframework.behavioralinterface.scoping;

import org.eclipse.xtext.xbase.scoping.XtypeScopeProvider;

public abstract class AbstractBehavioralInterfaceScopeProvider extends XtypeScopeProvider {
}
