/*
 * generated by Xtext 2.12.0
 */
package org.eclipse.gemoc.xdsmlframework.behavioralinterface.validation

import org.eclipse.gemoc.xdsmlframework.behavioralinterface.behavioralInterface.InputEvent
import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class BehavioralInterfaceValidator extends AbstractBehavioralInterfaceValidator {
	
	@Check
	def checkPreconditionParameters(InputEvent inputEvent) {
//		val ruleParameters = inputEvent.rule.parameters
//		val preconditionParameters = inputEvent.precondition.parameters
//		if (!ruleParameters.elementsEqual(preconditionParameters)) {
//			warning('Precondition must have the same parameters as execution rule', BehavioralInterfacePackage.Literals.INPUT_EVENT__PRECONDITION)
//		}
	}
}
