/*
 * generated by Xtext 2.12.0
 */
package org.eclipse.gemoc.xdsmlframework.behavioralinterface.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class BehavioralInterfaceGrammarAccess extends AbstractGrammarElementFinder {
	
	public class BehavioralInterfaceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.gemoc.xdsmlframework.behavioralinterface.BehavioralInterface.BehavioralInterface");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDslKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cDslNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cDslNameFQNParserRuleCall_1_0 = (RuleCall)cDslNameAssignment_1.eContents().get(0);
		private final Assignment cEventsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cEventsEventParserRuleCall_2_0 = (RuleCall)cEventsAssignment_2.eContents().get(0);
		
		//BehavioralInterface:
		//	'dsl' dslName=FQN
		//	events+=Event*;
		@Override public ParserRule getRule() { return rule; }
		
		//'dsl' dslName=FQN events+=Event*
		public Group getGroup() { return cGroup; }
		
		//'dsl'
		public Keyword getDslKeyword_0() { return cDslKeyword_0; }
		
		//dslName=FQN
		public Assignment getDslNameAssignment_1() { return cDslNameAssignment_1; }
		
		//FQN
		public RuleCall getDslNameFQNParserRuleCall_1_0() { return cDslNameFQNParserRuleCall_1_0; }
		
		//events+=Event*
		public Assignment getEventsAssignment_2() { return cEventsAssignment_2; }
		
		//Event
		public RuleCall getEventsEventParserRuleCall_2_0() { return cEventsEventParserRuleCall_2_0; }
	}
	public class EventElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.gemoc.xdsmlframework.behavioralinterface.BehavioralInterface.Event");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cInputEventParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cOutputEventParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Event:
		//	InputEvent | OutputEvent;
		@Override public ParserRule getRule() { return rule; }
		
		//InputEvent | OutputEvent
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//InputEvent
		public RuleCall getInputEventParserRuleCall_0() { return cInputEventParserRuleCall_0; }
		
		//OutputEvent
		public RuleCall getOutputEventParserRuleCall_1() { return cOutputEventParserRuleCall_1; }
	}
	public class InputEventElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.gemoc.xdsmlframework.behavioralinterface.BehavioralInterface.InputEvent");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInputKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameFQNParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cRuleKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cEqualsSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cRuleAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cRuleFQNParserRuleCall_4_0 = (RuleCall)cRuleAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cParamsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cParamsAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cParamsEventParameterParserRuleCall_5_1_0 = (RuleCall)cParamsAssignment_5_1.eContents().get(0);
		private final Group cGroup_5_2 = (Group)cGroup_5.eContents().get(2);
		private final Keyword cCommaKeyword_5_2_0 = (Keyword)cGroup_5_2.eContents().get(0);
		private final Assignment cParamsAssignment_5_2_1 = (Assignment)cGroup_5_2.eContents().get(1);
		private final RuleCall cParamsEventParameterParserRuleCall_5_2_1_0 = (RuleCall)cParamsAssignment_5_2_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cInterruptibleKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cEqualsSignKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cInterruptibleAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final Alternatives cInterruptibleAlternatives_6_2_0 = (Alternatives)cInterruptibleAssignment_6_2.eContents().get(0);
		private final Keyword cInterruptibleTrueKeyword_6_2_0_0 = (Keyword)cInterruptibleAlternatives_6_2_0.eContents().get(0);
		private final Keyword cInterruptibleFalseKeyword_6_2_0_1 = (Keyword)cInterruptibleAlternatives_6_2_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cPreconditionKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cEqualsSignKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cPreconditionAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cPreconditionFQNParserRuleCall_7_2_0 = (RuleCall)cPreconditionAssignment_7_2.eContents().get(0);
		
		//InputEvent:
		//	'input' name=FQN
		//	'rule' '=' rule=FQN ('params' params+=EventParameter (',' params+=EventParameter)*)? ('interruptible' '='
		//	interruptible?=('true' | 'false'))? ('precondition' '=' precondition=FQN)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'input' name=FQN 'rule' '=' rule=FQN ('params' params+=EventParameter (',' params+=EventParameter)*)? ('interruptible'
		//'=' interruptible?=('true' | 'false'))? ('precondition' '=' precondition=FQN)?
		public Group getGroup() { return cGroup; }
		
		//'input'
		public Keyword getInputKeyword_0() { return cInputKeyword_0; }
		
		//name=FQN
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//FQN
		public RuleCall getNameFQNParserRuleCall_1_0() { return cNameFQNParserRuleCall_1_0; }
		
		//'rule'
		public Keyword getRuleKeyword_2() { return cRuleKeyword_2; }
		
		//'='
		public Keyword getEqualsSignKeyword_3() { return cEqualsSignKeyword_3; }
		
		//rule=FQN
		public Assignment getRuleAssignment_4() { return cRuleAssignment_4; }
		
		//FQN
		public RuleCall getRuleFQNParserRuleCall_4_0() { return cRuleFQNParserRuleCall_4_0; }
		
		//('params' params+=EventParameter (',' params+=EventParameter)*)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'params'
		public Keyword getParamsKeyword_5_0() { return cParamsKeyword_5_0; }
		
		//params+=EventParameter
		public Assignment getParamsAssignment_5_1() { return cParamsAssignment_5_1; }
		
		//EventParameter
		public RuleCall getParamsEventParameterParserRuleCall_5_1_0() { return cParamsEventParameterParserRuleCall_5_1_0; }
		
		//(',' params+=EventParameter)*
		public Group getGroup_5_2() { return cGroup_5_2; }
		
		//','
		public Keyword getCommaKeyword_5_2_0() { return cCommaKeyword_5_2_0; }
		
		//params+=EventParameter
		public Assignment getParamsAssignment_5_2_1() { return cParamsAssignment_5_2_1; }
		
		//EventParameter
		public RuleCall getParamsEventParameterParserRuleCall_5_2_1_0() { return cParamsEventParameterParserRuleCall_5_2_1_0; }
		
		//('interruptible' '=' interruptible?=('true' | 'false'))?
		public Group getGroup_6() { return cGroup_6; }
		
		//'interruptible'
		public Keyword getInterruptibleKeyword_6_0() { return cInterruptibleKeyword_6_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_6_1() { return cEqualsSignKeyword_6_1; }
		
		//interruptible?=('true' | 'false')
		public Assignment getInterruptibleAssignment_6_2() { return cInterruptibleAssignment_6_2; }
		
		//('true' | 'false')
		public Alternatives getInterruptibleAlternatives_6_2_0() { return cInterruptibleAlternatives_6_2_0; }
		
		//'true'
		public Keyword getInterruptibleTrueKeyword_6_2_0_0() { return cInterruptibleTrueKeyword_6_2_0_0; }
		
		//'false'
		public Keyword getInterruptibleFalseKeyword_6_2_0_1() { return cInterruptibleFalseKeyword_6_2_0_1; }
		
		//('precondition' '=' precondition=FQN)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'precondition'
		public Keyword getPreconditionKeyword_7_0() { return cPreconditionKeyword_7_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_7_1() { return cEqualsSignKeyword_7_1; }
		
		//precondition=FQN
		public Assignment getPreconditionAssignment_7_2() { return cPreconditionAssignment_7_2; }
		
		//FQN
		public RuleCall getPreconditionFQNParserRuleCall_7_2_0() { return cPreconditionFQNParserRuleCall_7_2_0; }
	}
	public class OutputEventElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.gemoc.xdsmlframework.behavioralinterface.BehavioralInterface.OutputEvent");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOutputKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameFQNParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cRuleKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cEqualsSignKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cRuleAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cRuleFQNParserRuleCall_5_0 = (RuleCall)cRuleAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cParamsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cParamsAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cParamsEventParameterParserRuleCall_6_1_0 = (RuleCall)cParamsAssignment_6_1.eContents().get(0);
		private final Group cGroup_6_2 = (Group)cGroup_6.eContents().get(2);
		private final Keyword cCommaKeyword_6_2_0 = (Keyword)cGroup_6_2.eContents().get(0);
		private final Assignment cParamsAssignment_6_2_1 = (Assignment)cGroup_6_2.eContents().get(1);
		private final RuleCall cParamsEventParameterParserRuleCall_6_2_1_0 = (RuleCall)cParamsAssignment_6_2_1.eContents().get(0);
		
		//OutputEvent:
		//	'output' name=FQN ':'
		//	'rule' '=' rule=FQN ('params' params+=EventParameter (',' params+=EventParameter)*)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'output' name=FQN ':' 'rule' '=' rule=FQN ('params' params+=EventParameter (',' params+=EventParameter)*)?
		public Group getGroup() { return cGroup; }
		
		//'output'
		public Keyword getOutputKeyword_0() { return cOutputKeyword_0; }
		
		//name=FQN
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//FQN
		public RuleCall getNameFQNParserRuleCall_1_0() { return cNameFQNParserRuleCall_1_0; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//'rule'
		public Keyword getRuleKeyword_3() { return cRuleKeyword_3; }
		
		//'='
		public Keyword getEqualsSignKeyword_4() { return cEqualsSignKeyword_4; }
		
		//rule=FQN
		public Assignment getRuleAssignment_5() { return cRuleAssignment_5; }
		
		//FQN
		public RuleCall getRuleFQNParserRuleCall_5_0() { return cRuleFQNParserRuleCall_5_0; }
		
		//('params' params+=EventParameter (',' params+=EventParameter)*)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'params'
		public Keyword getParamsKeyword_6_0() { return cParamsKeyword_6_0; }
		
		//params+=EventParameter
		public Assignment getParamsAssignment_6_1() { return cParamsAssignment_6_1; }
		
		//EventParameter
		public RuleCall getParamsEventParameterParserRuleCall_6_1_0() { return cParamsEventParameterParserRuleCall_6_1_0; }
		
		//(',' params+=EventParameter)*
		public Group getGroup_6_2() { return cGroup_6_2; }
		
		//','
		public Keyword getCommaKeyword_6_2_0() { return cCommaKeyword_6_2_0; }
		
		//params+=EventParameter
		public Assignment getParamsAssignment_6_2_1() { return cParamsAssignment_6_2_1; }
		
		//EventParameter
		public RuleCall getParamsEventParameterParserRuleCall_6_2_1_0() { return cParamsEventParameterParserRuleCall_6_2_1_0; }
	}
	public class EventParameterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.gemoc.xdsmlframework.behavioralinterface.BehavioralInterface.EventParameter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameFQNParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeFQNParserRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		private final Assignment cManyAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cManyAsteriskKeyword_2_0 = (Keyword)cManyAssignment_2.eContents().get(0);
		
		//EventParameter:
		//	name=FQN type=FQN many?='*';
		@Override public ParserRule getRule() { return rule; }
		
		//name=FQN type=FQN many?='*'
		public Group getGroup() { return cGroup; }
		
		//name=FQN
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//FQN
		public RuleCall getNameFQNParserRuleCall_0_0() { return cNameFQNParserRuleCall_0_0; }
		
		//type=FQN
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//FQN
		public RuleCall getTypeFQNParserRuleCall_1_0() { return cTypeFQNParserRuleCall_1_0; }
		
		//many?='*'
		public Assignment getManyAssignment_2() { return cManyAssignment_2; }
		
		//'*'
		public Keyword getManyAsteriskKeyword_2_0() { return cManyAsteriskKeyword_2_0; }
	}
	public class FQNElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.gemoc.xdsmlframework.behavioralinterface.BehavioralInterface.FQN");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//FQN:
		//	ID ('.' ID)*;
		@Override public ParserRule getRule() { return rule; }
		
		//ID ('.' ID)*
		public Group getGroup() { return cGroup; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }
		
		//('.' ID)*
		public Group getGroup_1() { return cGroup_1; }
		
		//'.'
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}
	
	
	private final BehavioralInterfaceElements pBehavioralInterface;
	private final EventElements pEvent;
	private final InputEventElements pInputEvent;
	private final OutputEventElements pOutputEvent;
	private final EventParameterElements pEventParameter;
	private final FQNElements pFQN;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public BehavioralInterfaceGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pBehavioralInterface = new BehavioralInterfaceElements();
		this.pEvent = new EventElements();
		this.pInputEvent = new InputEventElements();
		this.pOutputEvent = new OutputEventElements();
		this.pEventParameter = new EventParameterElements();
		this.pFQN = new FQNElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.eclipse.gemoc.xdsmlframework.behavioralinterface.BehavioralInterface".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//BehavioralInterface:
	//	'dsl' dslName=FQN
	//	events+=Event*;
	public BehavioralInterfaceElements getBehavioralInterfaceAccess() {
		return pBehavioralInterface;
	}
	
	public ParserRule getBehavioralInterfaceRule() {
		return getBehavioralInterfaceAccess().getRule();
	}
	
	//Event:
	//	InputEvent | OutputEvent;
	public EventElements getEventAccess() {
		return pEvent;
	}
	
	public ParserRule getEventRule() {
		return getEventAccess().getRule();
	}
	
	//InputEvent:
	//	'input' name=FQN
	//	'rule' '=' rule=FQN ('params' params+=EventParameter (',' params+=EventParameter)*)? ('interruptible' '='
	//	interruptible?=('true' | 'false'))? ('precondition' '=' precondition=FQN)?;
	public InputEventElements getInputEventAccess() {
		return pInputEvent;
	}
	
	public ParserRule getInputEventRule() {
		return getInputEventAccess().getRule();
	}
	
	//OutputEvent:
	//	'output' name=FQN ':'
	//	'rule' '=' rule=FQN ('params' params+=EventParameter (',' params+=EventParameter)*)?;
	public OutputEventElements getOutputEventAccess() {
		return pOutputEvent;
	}
	
	public ParserRule getOutputEventRule() {
		return getOutputEventAccess().getRule();
	}
	
	//EventParameter:
	//	name=FQN type=FQN many?='*';
	public EventParameterElements getEventParameterAccess() {
		return pEventParameter;
	}
	
	public ParserRule getEventParameterRule() {
		return getEventParameterAccess().getRule();
	}
	
	//FQN:
	//	ID ('.' ID)*;
	public FQNElements getFQNAccess() {
		return pFQN;
	}
	
	public ParserRule getFQNRule() {
		return getFQNAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
