/**
 * generated by Xtext 2.12.0
 */
package org.eclipse.gemoc.xdsmlframework.behavioralinterface.behavioralInterface;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Input Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.gemoc.xdsmlframework.behavioralinterface.behavioralInterface.InputEvent#isInterruptible <em>Interruptible</em>}</li>
 *   <li>{@link org.eclipse.gemoc.xdsmlframework.behavioralinterface.behavioralInterface.InputEvent#getPrecondition <em>Precondition</em>}</li>
 * </ul>
 *
 * @see org.eclipse.gemoc.xdsmlframework.behavioralinterface.behavioralInterface.BehavioralInterfacePackage#getInputEvent()
 * @model
 * @generated
 */
public interface InputEvent extends Event
{
  /**
   * Returns the value of the '<em><b>Interruptible</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Interruptible</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Interruptible</em>' attribute.
   * @see #setInterruptible(boolean)
   * @see org.eclipse.gemoc.xdsmlframework.behavioralinterface.behavioralInterface.BehavioralInterfacePackage#getInputEvent_Interruptible()
   * @model
   * @generated
   */
  boolean isInterruptible();

  /**
   * Sets the value of the '{@link org.eclipse.gemoc.xdsmlframework.behavioralinterface.behavioralInterface.InputEvent#isInterruptible <em>Interruptible</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Interruptible</em>' attribute.
   * @see #isInterruptible()
   * @generated
   */
  void setInterruptible(boolean value);

  /**
   * Returns the value of the '<em><b>Precondition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Precondition</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Precondition</em>' attribute.
   * @see #setPrecondition(String)
   * @see org.eclipse.gemoc.xdsmlframework.behavioralinterface.behavioralInterface.BehavioralInterfacePackage#getInputEvent_Precondition()
   * @model
   * @generated
   */
  String getPrecondition();

  /**
   * Sets the value of the '{@link org.eclipse.gemoc.xdsmlframework.behavioralinterface.behavioralInterface.InputEvent#getPrecondition <em>Precondition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Precondition</em>' attribute.
   * @see #getPrecondition()
   * @generated
   */
  void setPrecondition(String value);

} // InputEvent
