/**
 * generated by Xtext 2.12.0
 */
package org.eclipse.gemoc.xdsmlframework.behavioralinterface.behavioralInterface;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Output Event</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.eclipse.gemoc.xdsmlframework.behavioralinterface.behavioralInterface.BehavioralInterfacePackage#getOutputEvent()
 * @model
 * @generated
 */
public interface OutputEvent extends Event
{
} // OutputEvent
